### PR TITLE
Fix document manipulation

### LINKED ISSUE #9: Insertion of children is broken for containers
Cmark has a very misleading naming of its arguments for inserting nodes: The `cmark_node_insert_after` function takes a `node` and a `sibling`. https://github.com/SwiftDocOrg/swift-cmark/blob/master/src/node.c#L719

Unlike what you would expect, `sibling` is the node that is actually _inserted_. Unfortunately CommonMark uses the wrong order of arguments for all calls to `cmark_node_insert_after`, e.g. at https://github.com/SwiftDocOrg/CommonMark/blob/master/Sources/CommonMark/Supporting%20Types/Children.swift#L111

### PR DESCRIPTION
**Pull request by Ehlster**
Fixes #9 

I'm not entirely happy with the mismatch of `sibling` now. Our sibling is exactly the other node than cmark's sibling. But I did not want to break the existing public API.

### CODE REVIEW

File: Tests/CommonMarkTests/ContainerManipulationTests.swift [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+        XCTAssertTrue(wasLineBreakInserted)
+        XCTAssertEqual(paragraph.children[1], lineBrake)
+    }
+    
+    func testListManipulation() throws {
+        let document = try Document(
+            #"""
+            * First
+            * Second
+            * Forth
```
Comment (mattt) [inline Tests/CommonMarkTests/ContainerManipulationTests.swift]:
```suggestion
            * Fourth
```

File: Tests/CommonMarkTests/ContainerManipulationTests.swift [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+        let fifth = List.Item(children: [Text(literal: "Fifth")])
+        let wasFithInserted = list.insert(child: fifth, after: list.children[3])
+        XCTAssertTrue(wasFithInserted)
+        XCTAssertEqual(list.children[4], fifth)
+    }
+
+    func testListItemManipulation() throws {
+
+        let listItem = List.Item(children: [Paragraph(text: "First")])
+
```
Comment (mattt) [inline Tests/CommonMarkTests/ContainerManipulationTests.swift]:
```suggestion
    func testListItemManipulation() throws {
        let listItem = List.Item(children: [Paragraph(text: "First")])
```

File: Tests/CommonMarkTests/ContainerManipulationTests.swift [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+        let text = Text(literal: "Article 1:")
+        let wasTextInserted = paragraph.insert(child: text, before: paragraph.children[0])
+        XCTAssertTrue(wasTextInserted)
+        XCTAssertEqual(paragraph.children[0], text)
+
+        let lineBrake = SoftLineBreak()
+        let wasLineBreakInserted = paragraph.insert(child: lineBrake, after: text)
+        XCTAssertTrue(wasLineBreakInserted)
+        XCTAssertEqual(paragraph.children[1], lineBrake)
```
Comment (mattt) [inline Tests/CommonMarkTests/ContainerManipulationTests.swift]:
```suggestion
        let lineBreak = SoftLineBreak()
        let wasLineBreakInserted = paragraph.insert(child: lineBreak, after: text)
        XCTAssertTrue(wasLineBreakInserted)
        XCTAssertEqual(paragraph.children[1], lineBreak)
```

File: Tests/CommonMarkTests/ContainerManipulationTests.swift [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+        XCTAssertEqual(list.children.count, 3)
+
+        let third = List.Item(children: [Text(literal: "Third")])
+        let wasThirdInserted = list.insert(child: third, before: list.children[2])
+        XCTAssertTrue(wasThirdInserted)
+        XCTAssertEqual(list.children[2], third)
+
+        let fifth = List.Item(children: [Text(literal: "Fifth")])
+        let wasFithInserted = list.insert(child: fifth, after: list.children[3])
+        XCTAssertTrue(wasFithInserted)
```
Comment (mattt) [inline Tests/CommonMarkTests/ContainerManipulationTests.swift]:
```suggestion
        let wasFifthInserted = list.insert(child: fifth, after: list.children[3])
        XCTAssertTrue(wasFifthInserted)
```

**Review by mattt — CHANGES_REQUESTED** [review]

**Review by mattt — APPROVED** [review]

**Comment by mattt** [comment]
Gut gemacht, @Lukas-Stuehrk! My only feedback had to do with some annoying quirks of English spelling. If nothing else, it was an excuse to do a batched commit of [PR suggestions](https://mobile.twitter.com/mattt/status/1252289846493626372), which worked great.

But seriously, kudos for writing some truly excellent tests. And thanks so much for identifying and fixing this issue in the first place. I'm sorry that I missed that cue from cmark's API and neglected to exercise that functionality entirely. Very happy to have this in here now, though.

**Comment by Ehlster** [comment]
You're welcome! It was a little bit too late in the evening to proofread English spelling 😴 

And I did not know PR suggestions! So thank you for applying, I know a great tool now which I can utilize in the future.
